"""Kagikai CrewAI tools: Bitcoin escrow for AI agents."""

__version__ = "0.7.0"

from kagikai_crewai.tools import (
    KagikaiHealthTool,
    KagikaiCreateInstrumentTool,
    KagikaiConfirmInstrumentTool,
    KagikaiVerifyAddressTool,
    KagikaiGetAttestationTool,
    KagikaiGetStatusTool,
    KagikaiCreateBatchTool,
    KagikaiGetBatchStatusTool,
    KagikaiWatchReceiptTool,
    KagikaiDeleteWatchTool,
    KagikaiGetAgentTool,
    KagikaiUpdateAgentTool,
    KagikaiGetAgentCardTool,
    KagikaiGetReputationTool,
    KagikaiSubmitInstrumentTool,
    KagikaiCompleteInstrumentTool,
    KagikaiRejectInstrumentTool,
    KagikaiVerifyTdxQuoteTool,
    KagikaiEscrowCreateTool,
    KagikaiEscrowStatusTool,
    KagikaiEscrowReleaseTool,
    KagikaiEscrowCancelTool,
    KagikaiSetDestinationTool,
    KagikaiListAvailableTool,
    KagikaiRecycleInstrumentTool,
    KagikaiRefundInstrumentTool,
    KagikaiFeeEstimateTool,
    KagikaiDisputeInstrumentTool,
    KagikaiResolveDisputeTool,
    kagikai_tools,
)

__all__ = [
    "KagikaiHealthTool",
    "KagikaiCreateInstrumentTool",
    "KagikaiConfirmInstrumentTool",
    "KagikaiVerifyAddressTool",
    "KagikaiGetAttestationTool",
    "KagikaiGetStatusTool",
    "KagikaiCreateBatchTool",
    "KagikaiGetBatchStatusTool",
    "KagikaiWatchReceiptTool",
    "KagikaiDeleteWatchTool",
    "KagikaiGetAgentTool",
    "KagikaiUpdateAgentTool",
    "KagikaiGetAgentCardTool",
    "KagikaiGetReputationTool",
    "KagikaiSubmitInstrumentTool",
    "KagikaiCompleteInstrumentTool",
    "KagikaiRejectInstrumentTool",
    "KagikaiVerifyTdxQuoteTool",
    "KagikaiEscrowCreateTool",
    "KagikaiEscrowStatusTool",
    "KagikaiEscrowReleaseTool",
    "KagikaiEscrowCancelTool",
    "KagikaiSetDestinationTool",
    "KagikaiListAvailableTool",
    "KagikaiRecycleInstrumentTool",
    "KagikaiRefundInstrumentTool",
    "KagikaiFeeEstimateTool",
    "KagikaiDisputeInstrumentTool",
    "KagikaiResolveDisputeTool",
    "kagikai_tools",
]
